version: '3.8'

# Services
services:
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # Nginx Service
  nginx:
    image: nginx:1.19
    ports:
      - 80:80
    volumes:
      - ./:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP Service
  php:
    build: ./.docker/php
    working_dir: /var/www/php
    volumes:
      - ./:/var/www/php
  # MySQL Service
  mysql:
    image: mysql:5.7
    container_name: mysqlHost
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookexchange
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10
    ports:
      - 3306:3306
# Volumes
volumes:

  mysqldata:
